### ISSUE TITLE
Tickets list limited to 100 items

### ISSUE THREAD

**Issue by thomj** [mojohelpdesk/mojohelpdesk-api-doc#5]
Hi
I'm trying to create an office dashboard utilising the API, listing each agents number of open tickets but the results of the JSON feed are capped at 100 items even though I'm requesting 1000 items.

The url I'm using is:
    http://patronbase.mojohelpdesk.com/api/tickets/search.json?query=assignee.id:#######+AND+status.id:\(\<50\)\&access_key=########\&per_page=1000

Is it possible to increase this limit?

Thanks
Thom

**Comment by ivobg** [comment]
Hi Thom,

Sorry for the late answer. We limited the number of items to 100 due to performance considerations.
You can always create a loop and use 'page' parameter to grab all the results.

Regards,
Ivaylo
