### ISSUE TITLE
Not getting latest data after created in account by api call

### ISSUE THREAD

**Issue by Gajendracis** [mojohelpdesk/mojohelpdesk-api-doc#6]
Hi,

I'm making a call to get the list of tickets of my account but I am able to get the tickets, but not latest, only previous created tickets I am getting , but after some time (1/2 hour) I am able to get the latest ticket by api call, Why I am not able to get the data immediately after creating tickets.

I am using following api call
curl -H 'Accept: application/xml' -H 'Content-type: application/xml' http://mysupport.mojohelpdesk.com/api/tickets.json?access_key={{access_key}}

**Comment by ivobg** [comment]
There is some time lag between ticket creation and indexing it in the search index (from where the above mention API call is getting the data). Usually the lag is just few seconds. 1/2 hour lag is indeed big, and might be caused by some temporary network issues.
