### ISSUE TITLE
Webhook support?

### ISSUE THREAD

**Issue by itslenny** [mojohelpdesk/mojohelpdesk-api-doc#9]
Hi,

I want to route ticket creation to slack. I set it up with Zapier, but their platform is too limited for what I want (I want to route different ticket types to different rooms, and they have a limit of 3 paths).

Is there support for web hooks on mojo or do I just need to poll your API on an interval?

Please advise.

thank you,

Lenny

**Comment by wpozzarPHSDEV** [comment]
I am also looking for some kind of web hook to link to Slack.

**Comment by Loufi1** [comment]
Is there any updates about webhook ? I am also looking for a way to notify when a new ticket has been created.

**Comment by mojo-ivaylo** [comment]
Hi all,

I'm sorry for the late response - unfortunately there is no webhook support at the moment. Since it was requested several times in the past (not too often), we might consider adding it, but it is yet to be decided how it should be implemented and when.

Regards,
Ivaylo Georgiev
